Modify provisioner and CI workflow shell scripts
Signed-off-by: Pankaj Walke <pankaj.walke@mavs.uta.edu>

diff --git a/stacks/cicd/backstage-templates/entities/ci-cd/infra/ci-cd/chart/templates/ci-workflow.yaml b/stacks/cicd/backstage-templates/entities/ci-cd/infra/ci-cd/chart/templates/ci-workflow.yaml
--- a/stacks/cicd/backstage-templates/entities/ci-cd/infra/ci-cd/chart/templates/ci-workflow.yaml
+++ b/stacks/cicd/backstage-templates/entities/ci-cd/infra/ci-cd/chart/templates/ci-workflow.yaml
@@ -157,13 +157,12 @@ spec:
         args:
           - -c
           - >-
-            #!/bin/sh
-            set -eu;
-            [ -z "${ARGO_TOKEN:-}" ] && echo "Error: ARGO_TOKEN not set" && exit 1;
-            apk add --no-cache curl jq;
-            cd_workflow_url="https://{{`{{inputs.parameters.workflow-event-url}}`}}";
-            image_tag="{{`{{inputs.parameters.image-tag}}`}}";
-            app_name="{{`{{inputs.parameters.app-name}}`}}";
+            set -eu &&
+            [ -z "${ARGO_TOKEN:-}" ] && echo "Error: ARGO_TOKEN not set" && exit 1 &&
+            apk add --no-cache curl jq &&
+            cd_workflow_url="https://{{`{{inputs.parameters.workflow-event-url}}`}}" &&
+            image_tag="{{`{{inputs.parameters.image-tag}}`}}" &&
+            app_name="{{`{{inputs.parameters.app-name}}`}}" &&
             for i in $(seq 1 3); do
               if curl -k -sf \
                 -X POST \
@@ -171,11 +170,11 @@ spec:
                 -H "Authorization: Bearer ${ARGO_TOKEN}" \
                 -d "{\"image_tag\":\"${image_tag}\", \"app_name\":\"${app_name}\"}" \
                 "${cd_workflow_url}"; then
-                echo "CD workflow invoked successfully";
-                exit 0;
-              fi;
-              [ $i -eq 3 ] && echo "All retries failed" && exit 1;
-              echo "Attempt $i failed. Retrying..." && sleep 5;
+                echo "CD workflow invoked successfully"
+                exit 0
+              fi
+              [ $i -eq 3 ] && echo "All retries failed" && exit 1
+              echo "Attempt $i failed. Retrying..." && sleep 5
             done
 ---
 apiVersion: argoproj.io/v1alpha1
diff --git a/stacks/cicd/backstage-templates/entities/ci-cd/infra/ci-cd/chart/templates/provisioner.yaml b/stacks/cicd/backstage-templates/entities/ci-cd/infra/ci-cd/chart/templates/provisioner.yaml
--- a/stacks/cicd/backstage-templates/entities/ci-cd/infra/ci-cd/chart/templates/provisioner.yaml
+++ b/stacks/cicd/backstage-templates/entities/ci-cd/infra/ci-cd/chart/templates/provisioner.yaml
@@ -30,12 +30,12 @@ spec:
           args:
             - -c
             - >-
-              set -eu;
+              set -eu &&
               for var in GITEA_USERNAME GITEA_PASSWORD HOOKS_API_URL GITEA_TOKEN ARGO_TOKEN WEBHOOK_URL; do
-                [ -z "$(eval echo \$$var)" ] && echo "Error: $var not set" && exit 1;
-              done;
-              apk add --no-cache curl yq jq;
-              gitea_auth=$(echo -n "${GITEA_USERNAME}:${GITEA_PASSWORD}" | base64);
+                [ -z "$(eval echo \$$var)" ] && echo "Error: $var not set" && exit 1
+              done &&
+              apk add --no-cache curl yq jq &&
+              gitea_auth=$(echo -n "${GITEA_USERNAME}:${GITEA_PASSWORD}" | base64) &&
               cat > docker_config.yaml << EOF
               apiVersion: v1
               kind: ConfigMap
@@ -45,9 +45,8 @@ spec:
               data:
                 config.json: |
                   {"auths":{"{{ .Values.giteaBaseUrl }}":{"auth":"${gitea_auth}"}}}
-              EOF
-              ;
-              kubectl apply -f docker_config.yaml || exit 1;
+              EOF &&
+              kubectl apply -f docker_config.yaml || exit 1 &&
               for i in $(seq 1 3); do
                 if curl -k -X POST "${HOOKS_API_URL}" \
                   -H "accept: application/json" \
@@ -55,11 +54,11 @@ spec:
                   -H "Content-Type: application/json" \
                   -d "{\"branch_filter\":\"main\",\"type\":\"gitea\",\"events\":[\"push\"],\"authorization_header\":\"Bearer ${ARGO_TOKEN}\",\"config\":{\"url\":\"${WEBHOOK_URL}\",\"content_type\":\"json\"},\"active\":true}" \
                   -fsS; then
-                  echo "Webhook created successfully";
-                  exit 0;
-                fi;
-                [ $i -eq 3 ] && echo "All retries failed" && exit 1;
-                echo "Attempt $i failed. Retrying..." && sleep 5;
+                  echo "Webhook created successfully"
+                  exit 0
+                fi
+                [ $i -eq 3 ] && echo "All retries failed" && exit 1
+                echo "Attempt $i failed. Retrying..." && sleep 5
               done
 ---
 apiVersion: external-secrets.io/v1beta1
